from fastapi import FastAPI

from routers import (
    agent_workspace,
    campus_sources,
    clipboard,
    completion_notifications,
    content,
    content_analyses,
    cookie,
    creator_sources,
    download,
    favorite_sources,
    folder_import_watcher,
    ingest,
    inbox,
    knowledge,
    llm_settings,
    manual_collection,
    markdown,
    media,
    media_tools,
    miniprogram_forum,
    obsidian,
    openclaw,
    openclaw_reports,
    paddle_ocr_settings,
    parse,
    pipeline,
    prompts,
    qa,
    rss_sources,
    runtime_components,
    search,
    source_sync_tasks,
    summarize,
    tasks,
    telegram,
    telemetry,
    transcribe,
    update,
    uploads,
    video_settings,
    wechat_content_filters,
    wechat_discovery,
    wechat_feed,
    wechat_publishing,
    wechat_reports,
    wechat_subscriptions,
)


API_ROUTERS = (
    (parse.router, "parse"),
    (download.router, "download"),
    (transcribe.router, "transcribe"),
    (summarize.router, "summarize"),
    (pipeline.router, "pipeline"),
    (cookie.router, "cookie"),
    (tasks.router, "tasks"),
    (uploads.router, "uploads"),
    (qa.router, "qa"),
    (knowledge.router, "knowledge"),
    (clipboard.router, "clipboard"),
    (folder_import_watcher.router, "folder-import-watcher"),
    (prompts.router, "prompts"),
    (inbox.router, "inbox"),
    (search.router, "search"),
    (content.router, "content"),
    (content_analyses.router, "content-analyses"),
    (markdown.router, "markdown"),
    (media.router, "media"),
    (telegram.router, "telegram"),
    (ingest.router, "ingest"),
    (obsidian.router, "obsidian"),
    (openclaw.router, "openclaw"),
    (openclaw_reports.router, "openclaw-reports"),
    (agent_workspace.router, "agent-workspace"),
    (wechat_subscriptions.router, "wechat-subscriptions"),
    (wechat_discovery.router, "wechat-discovery"),
    (wechat_feed.router, "wechat-feed"),
    (wechat_content_filters.router, "wechat-content-filters"),
    (media_tools.router, "media-tools"),
    (llm_settings.router, "llm-settings"),
    (paddle_ocr_settings.router, "paddle-ocr-settings"),
    (wechat_reports.router, "wechat-reports"),
    (wechat_publishing.router, "wechat-publishing"),
    (campus_sources.router, "campus-sources"),
    (runtime_components.router, "runtime-components"),
    (miniprogram_forum.router, "miniprogram-forum"),
    (creator_sources.router, "creator-sources"),
    (manual_collection.router, "manual-collection"),
    (rss_sources.router, "rss-sources"),
    (favorite_sources.router, "favorite-sources"),
    (source_sync_tasks.router, "source-sync-tasks"),
    (video_settings.router, "video-settings"),
    (update.router, "updates"),
    (telemetry.router, "telemetry"),
    (completion_notifications.router, "completion-notifications"),
)


def register_api_routers(app: FastAPI) -> None:
    for router, tag in API_ROUTERS:
        app.include_router(router, prefix="/api", tags=[tag])
